# **Sentiment Analysis**

Sentiment Analysis is a technique used in computers to understand human emotions from text. It helps to show a piece of text expresses a positive, negative, or neutral feeling. The goal that Sentiment mining tries to gain is to be analysed people’s opinions in a way that can help businesses expand. It focuses not only on polarity (positive, negative & neutral) but also on emotions (happy, sad, angry, etc.).



# Why is Sentiment Analysis Important?
Sentiment analysis is a way for computers to understand the feelings behind words. It helps businesses know if people feel positive, negative, or neutral about their brand or product. This helps them decide if their product will be popular in the market.



# Some reasons why sentiment analysis is important for business:

**Customer Feedback Analysis:** Businesses can analyze customer reviews, comments, and feedback to understand the sentiment behind them helping in identifying areas for improvement and addressing customer concerns, ultimately enhancing customer satisfaction

**Marketing Campaign Effectiveness:**
Businesses can evaluate the success of their marketing campaigns by analyzing the sentiment of online discussions and social media mentions.
Positive sentiment indicates that the campaign is resonating with the target audience, while negative sentiment may signal the need for adjustments.

# What are the Types of Sentiment Analysis?

**1.Fine-Grained Sentiment Analysis:**
This depends on the polarity base. This category can be designed as very positive, positive, neutral, negative, or very negative. The rating is done on a scale of 1 to 5. If the rating is 5 then it is very positive, 2 then negative, and 3 then neutral.

**2.Emotion detection:**
The sentiments happy, sad, angry, upset, jolly, pleasant, and so on come under emotion detection. It is also known as a lexicon method of sentiment analysis.

**3.Aspect-Based Sentiment Analysis:**
It focuses on a particular aspect for instance if a person wants to check the feature of the cell phone then it checks the aspect such as the battery, screen, and camera quality then aspect based is used.

**4.Multilingual Sentiment Analysis:**

Multilingual consists of different languages where the classification needs to be done as positive, negative, and neutral. This is highly challenging and comparatively difficult.


   # **1.Install and Import Dependencies**
   # **2.Instantiate Model**
   # **3.Encode and Calculate Sentiment**
   # **4.Collect Reviews**
   # **5.Load Reviews into DataFrame and Score**
   

# **1.Install and Import Dependencies**


In [1]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


In [2]:
!pip install transformers requests beautifulsoup4 pandas numpy

In [3]:
 from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch  
import requests  
from bs4 import BeautifulSoup    
import re        # extract the specifiic comments 

# **2. Instantiate Model**

In [4]:
tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')
model =AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/669M [00:00<?, ?B/s]

# **3.Encode and Calculate Sentiment**

In [5]:
tokens=tokenizer.encode('It was good but couldve been better.Great',return_tensors='pt')


In [6]:
tokens

tensor([[  101, 10197, 10140, 12050, 10502, 12296, 10598, 10662, 16197,   119,
         11838,   102]])

In [7]:
tokens[0]


tensor([  101, 10197, 10140, 12050, 10502, 12296, 10598, 10662, 16197,   119,
        11838,   102])

In [8]:
tokenizer.decode(tokens[0])

'[CLS] it was good but couldve been better. great [SEP]'

In [9]:
result=model(tokens)

In [10]:
result

SequenceClassifierOutput(loss=None, logits=tensor([[-2.7768, -1.2353,  1.4419,  1.9804,  0.4584]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [11]:
result.logits

tensor([[-2.7768, -1.2353,  1.4419,  1.9804,  0.4584]],
       grad_fn=<AddmmBackward0>)

In [12]:
int(torch.argmax(result.logits))+1

4

# **4.Collect Reviews**

In [13]:
r=requests.get('https://www.yelp.com/biz/mejico-sydney-2')
soup=BeautifulSoup(r.text,'html.parser')
regex=re.compile('.*comment.*')  # extract a specific comment on that web page 
results=soup.find_all('p',{'class':regex})
reviews=[result.text for result in results]

In [20]:
results # All Different Review 

[<p class="comment__09f24__D0cxf y-css-1wfz87z"><span class="raw__09f24__T4Ezm" lang="en">Seated without a booking on a super busy Saturday night. Lovely, warm, and Theo right hostess also looked after our table and went out of her way to give detailed ingredients in every dish to avoid allergies for one of us. And the food was great! Guacamole made right at our table, everything prepared with our allergies in mind, and great dish recommendations. We'd been visiting Sydney for about a week from Melbourne, and this was by far our best dining experience. I'd definitely return here in the future.</span></p>,
 <p class="comment__09f24__D0cxf y-css-1wfz87z"><span class="raw__09f24__T4Ezm" lang="en">The food was decent not great..  We had the guacamole which was bland and came with some type of plantain chips.. The chicken and steak tacos were good.. But the service was poor. We had a waitress with an attitude. She seemed upset whenever we asked for anything.  She would walk by and just stic

In [22]:
results[0].text

"Seated without a booking on a super busy Saturday night. Lovely, warm, and Theo right hostess also looked after our table and went out of her way to give detailed ingredients in every dish to avoid allergies for one of us. And the food was great! Guacamole made right at our table, everything prepared with our allergies in mind, and great dish recommendations. We'd been visiting Sydney for about a week from Melbourne, and this was by far our best dining experience. I'd definitely return here in the future."

# **5.Load Reviews into DataFrame and Score**

In [25]:
import pandas as pd 
import numpy as np

In [29]:
df = pd.DataFrame(np.array(reviews), columns=['review'])

In [30]:
df.head()

review
0  Seated without a booking on a super busy Satur...
1  The food was decent not great..  We had the gu...
2  Food was okay, guacamole was below average. Se...
3  Don't come here expecting legit Mexican food b...
4  Out of all the restaurants that I tried in Syd...

In [33]:
df.tail()

review
5  The food and service here was really good.  It...
6  Visiting from Texas and decided to give this r...
7  Great atmosphere, attentive service, solid mar...
8  We came here on a Thursday night @ 5pm and by ...
9  The food is fresh and tasty.  The scallop cevi...

In [34]:
df['review'].iloc[0]

"Seated without a booking on a super busy Saturday night. Lovely, warm, and Theo right hostess also looked after our table and went out of her way to give detailed ingredients in every dish to avoid allergies for one of us. And the food was great! Guacamole made right at our table, everything prepared with our allergies in mind, and great dish recommendations. We'd been visiting Sydney for about a week from Melbourne, and this was by far our best dining experience. I'd definitely return here in the future."

In [36]:
def sentiment_score(review):
    tokens=tokenizer.encode(review,return_tensors='pt')
    result=model(tokens)
    return int(torch.argmax(result.logits))+1

In [37]:
sentiment_score(df['review'].iloc[1])

2

In [40]:
df['sentiment']=df['review'].apply(lambda x: sentiment_score(x[:512]))
df['review']

0    Seated without a booking on a super busy Satur...
1    The food was decent not great..  We had the gu...
2    Food was okay, guacamole was below average. Se...
3    Don't come here expecting legit Mexican food b...
4    Out of all the restaurants that I tried in Syd...
5    The food and service here was really good.  It...
6    Visiting from Texas and decided to give this r...
7    Great atmosphere, attentive service, solid mar...
8    We came here on a Thursday night @ 5pm and by ...
9    The food is fresh and tasty.  The scallop cevi...
Name: review, dtype: object

In [41]:
df

review  sentiment
0  Seated without a booking on a super busy Satur...          5
1  The food was decent not great..  We had the gu...          2
2  Food was okay, guacamole was below average. Se...          2
3  Don't come here expecting legit Mexican food b...          3
4  Out of all the restaurants that I tried in Syd...          5
5  The food and service here was really good.  It...          5
6  Visiting from Texas and decided to give this r...          5
7  Great atmosphere, attentive service, solid mar...          3
8  We came here on a Thursday night @ 5pm and by ...          4
9  The food is fresh and tasty.  The scallop cevi...          4

In [43]:
df['review'].iloc[5]

'The food and service here was really good.  It was more like tapas food than Mexican food!  The drinks were amazing too!'

In [44]:
df['review'].iloc[8]

'We came here on a Thursday night @ 5pm and by 6pm the place was packed. A lovely big restaurant with a bar at the front (which is a bit awkward to try and push past everyone to get to your table). Friendly, helpful staff which is always a good start. The menu is large so we went with the "feed me" selection. All you need to do is sit back and let the chef feed you. As the other reviewers have stated the corn is a highlight and the pulled pork tacos, the sangria wasn\'t bad either.Loved the Mexican tapas style food and will be back.'